# Generated by Django 5.1.3 on 2024-11-28 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_control', '0002_account_subcategory'),
    ]

    operations = [
    ]
