# Generated by Django 5.1.3 on 2024-11-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_control', '0003_auto_20241127_2309'),
    ]

    operations = [
    ]
