# Generated by Django 5.1.3 on 2024-11-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_control', '0004_transaction_user'),
        ('finance_control', '0005_goal'),
    ]

    operations = [
    ]
